FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

COPY . .

# Disable Next.js telemetry
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PORT
ENV PORT=${NEXT_PORT}

EXPOSE ${PORT}

CMD ["npm", "run", "dev"]
